// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #009
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Forex
// Timeframe: H4

//@version=5
indicator("Price_Action_9", shorttitle="Price_Ac", overlay=false)

// Parâmetros
length = input.int(20, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
lowest = ta.lowest(low, length)

// Plot
plot(lowest, "Price_Action_9", color=color.green)
