// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #001
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Crypto
// Timeframe: M5

//@version=5
indicator("Stochastic_Custom_1", shorttitle="Stochast", overlay=true)

// Parâmetros
length = input.int(20, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
bb = ta.bb(source, length, 2)

// Plot
plot(bb, "Stochastic_Custom_1", color=color.purple)
