// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #046
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Crypto
// Timeframe: M5

//@version=5
indicator("Correlation_Matrix_46", shorttitle="Correlat", overlay=true)

// Parâmetros
length = input.int(14, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
atr = ta.atr(length)

// Plot
plot(atr, "Correlation_Matrix_46", color=color.lime)
