// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #043
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Crypto
// Timeframe: H1

//@version=5
indicator("Volatility_Index_43", shorttitle="Volatili", overlay=false)

// Parâmetros
length = input.int(21, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
volume_ma = ta.sma(volume, length)

// Plot
plot(volume_ma, "Volatility_Index_43", color=color.green)
