// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #016
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Crypto
// Timeframe: M5

//@version=5
indicator("Divergence_Hunter_16", shorttitle="Divergen", overlay=false)

// Parâmetros
length = input.int(200, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
volume_ma = ta.sma(volume, length)

// Plot
plot(volume_ma, "Divergence_Hunter_16", color=color.purple)
