// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #065
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Indices
// Timeframe: M1

//@version=5
indicator("Market_Structure_65", shorttitle="Market_S", overlay=true)

// Parâmetros
length = input.int(100, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
volume_ma = ta.sma(volume, length)

// Plot
plot(volume_ma, "Market_Structure_65", color=color.aqua)
