/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/

#property indicator_chart_window

extern string note1 = "Change font colors automatically? True = Yes";
extern bool Bid_Ask_Colors = FALSE;
extern bool ShowSymbol = TRUE;
extern bool ShowPeriod = TRUE;
extern bool ShowPrice = TRUE;
extern string note2 = "Default Font Color";
extern color FontColor = Yellow;
extern string note3 = "Font Size";
extern int FontSize = 26;
extern string note4 = "Font Type";
extern string FontType = "Arial Bold";
extern string note5 = "Display the price in what corner?";
extern string note6 = "Upper left=0; Upper right=1";
extern string note7 = "Lower left=2; Lower right=3";
extern int WhatCorner = 3;
double g_bid_168;

int init() {
   deleteobjects();
   return (0);
}

int deinit() {
   deleteobjects();
   return (0);
}

int start() {
   string l_dbl2str_8;
   if (Bid_Ask_Colors == TRUE) {
      if (Bid > g_bid_168) FontColor = LawnGreen;
      if (Bid < g_bid_168) FontColor = Red;
      g_bid_168 = Bid;
   }
   int l_y_0 = 1;
   int li_4 = 30;
   if (ShowPrice) {
      l_dbl2str_8 = DoubleToStr(Bid, Digits);
      ObjectCreate("Market_Price_Label", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("Market_Price_Label", l_dbl2str_8, FontSize, FontType, FontColor);
      ObjectSet("Market_Price_Label", OBJPROP_CORNER, WhatCorner);
      ObjectSet("Market_Price_Label", OBJPROP_XDISTANCE, 1);
      ObjectSet("Market_Price_Label", OBJPROP_YDISTANCE, l_y_0);
      l_y_0 += li_4;
   } else ObjectDelete("Market_Price_Label");
   if (ShowPeriod) {
      ObjectCreate("Period_Label", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("Period_Label", PeriodStr(Period()), FontSize, FontType, FontColor);
      ObjectSet("Period_Label", OBJPROP_CORNER, WhatCorner);
      ObjectSet("Period_Label", OBJPROP_XDISTANCE, 1);
      ObjectSet("Period_Label", OBJPROP_YDISTANCE, l_y_0);
      l_y_0 += li_4;
   } else ObjectDelete("Period_Label");
   if (ShowSymbol) {
      ObjectCreate("Symbol_Label", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("Symbol_Label", Symbol(), FontSize, FontType, FontColor);
      ObjectSet("Symbol_Label", OBJPROP_CORNER, WhatCorner);
      ObjectSet("Symbol_Label", OBJPROP_XDISTANCE, 1);
      ObjectSet("Symbol_Label", OBJPROP_YDISTANCE, l_y_0);
      l_y_0 += li_4;
   } else ObjectDelete("Symbol_Label");
   return (0);
}

string PeriodStr(int ai_0) {
   switch (ai_0) {
   case 1:
      return ("M1");
   case 5:
      return ("M5");
   case 15:
      return ("M15");
   case 30:
      return ("M30");
   case 60:
      return ("H1");
   case 240:
      return ("H4");
   case 1440:
      return ("D1");
   case 10080:
      return ("W1");
   case 43200:
      return ("MN");
   }
   return (Period());
}

void deleteobjects() {
   ObjectDelete("Market_Price_Label");
   ObjectDelete("Period_Label");
   ObjectDelete("Symbol_Label");
}
