/*
   Generated by EX4-TO-MQ4 decompiler V4.0.438.4 [-]
   Website: https://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "RoboFxId.Com"
#property link      "http://robofxid.com "

#property indicator_separate_window
#property indicator_minimum 0.0
#property indicator_maximum 120.0
#property indicator_buffers 3
#property indicator_color1 Orange
#property indicator_color2 Green
#property indicator_color3 Red

extern int level = 20;
double gda_80[];
double gda_84[];
double gda_88[];

int init() {
   SetIndexStyle(0, DRAW_HISTOGRAM, STYLE_SOLID, 3);
   SetIndexBuffer(0, gda_80);
   SetIndexStyle(1, DRAW_HISTOGRAM, STYLE_SOLID, 3);
   SetIndexBuffer(1, gda_84);
   SetIndexStyle(2, DRAW_HISTOGRAM, STYLE_SOLID, 3);
   SetIndexBuffer(2, gda_88);
   IndicatorShortName("robofxid_movement");
   return (0);
}

int start() {
   double ld_12;
   double ld_20;
   double ld_28;
   double ld_36;
   double ld_44;
   double ld_52;
   int li_60;
   int li_64;
   int li_68;
   int li_0 = IndicatorCounted();
   if (li_0 < 0) return (-1);
   if (li_0 > 0) li_0--;
   int li_8 = Bars - li_0;
   for (int li_4 = li_8 - 1; li_4 >= 0; li_4--) {
      ld_12 = iADX(NULL, 0, 10, PRICE_WEIGHTED, MODE_MAIN, li_4 + 0);
      ld_20 = iADX(NULL, 0, 10, PRICE_WEIGHTED, MODE_PLUSDI, li_4 + 0);
      ld_28 = iADX(NULL, 0, 10, PRICE_WEIGHTED, MODE_MINUSDI, li_4 + 0);
      ld_36 = iADX(NULL, 0, 10, PRICE_WEIGHTED, MODE_MAIN, li_4 + 1);
      ld_44 = iADX(NULL, 0, 10, PRICE_WEIGHTED, MODE_PLUSDI, li_4 + 1);
      ld_52 = iADX(NULL, 0, 10, PRICE_WEIGHTED, MODE_MINUSDI, li_4 + 1);
      li_60 = ld_12;
      li_64 = ld_20;
      li_68 = ld_28;
      if (ld_12 > level && ld_20 > ld_44 && ld_28 < ld_52) {
         gda_80[li_4] = 0;
         gda_84[li_4] = 50;
         gda_88[li_4] = 0;
      } else {
         if (ld_12 > level && ld_28 > ld_52 && ld_20 < ld_44) {
            gda_80[li_4] = 0;
            gda_84[li_4] = 0;
            gda_88[li_4] = 50;
         } else {
            gda_80[li_4] = 50;
            gda_84[li_4] = 0;
            gda_88[li_4] = 0;
         }
      }
      if (ld_12 > level && ld_20 > ld_44 && ld_28 < ld_52 && ld_12 > ld_36) {
         gda_80[li_4] = 0;
         gda_84[li_4] = 80;
         gda_88[li_4] = 0;
      } else {
         if (ld_12 > level && ld_28 > ld_52 && ld_20 < ld_44 && ld_12 > ld_36) {
            gda_80[li_4] = 0;
            gda_84[li_4] = 0;
            gda_88[li_4] = 80;
         }
      }
   }
   RefreshRates();
   return (0);
}
