// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #021
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Forex
// Timeframe: M5

//@version=5
indicator("Volatility_Index_21", shorttitle="Volatili", overlay=false)

// Parâmetros
length = input.int(21, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
macd = ta.macd(source, length, length*2, length//2)

// Plot
plot(macd, "Volatility_Index_21", color=color.lime)
