// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #027
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Forex
// Timeframe: M15

//@version=5
indicator("MACD_Pro_27", shorttitle="MACD_Pro", overlay=true)

// Parâmetros
length = input.int(50, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
ma = ta.sma(source, length)

// Plot
plot(ma, "MACD_Pro_27", color=color.purple)
