// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #058
// Tipo: INDICATOR
// Categoria: SMC
// Mercado: Crypto
// Timeframe: H1

//@version=5
indicator("Order_Blocks_58", shorttitle="Order_Bl", overlay=false)

// Parâmetros
length = input.int(14, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
ema = ta.ema(source, length)

// Plot
plot(ema, "Order_Blocks_58", color=color.lime)
