// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #059
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Indices
// Timeframe: H4

//@version=5
indicator("Support_Resistance_59", shorttitle="Support_", overlay=false)

// Parâmetros
length = input.int(14, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
macd = ta.macd(source, length, length*2, length//2)

// Plot
plot(macd, "Support_Resistance_59", color=color.orange)
