// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #044
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Indices
// Timeframe: H4

//@version=5
indicator("Volume_Flow_44", shorttitle="Volume_F", overlay=true)

// Parâmetros
length = input.int(14, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
rsi = ta.rsi(source, length)

// Plot
plot(rsi, "Volume_Flow_44", color=color.blue)
