// Criado em: 2025-08-13 11:09:10
// Arquivo de teste #032
// Tipo: INDICATOR
// Categoria: Technical
// Mercado: Indices
// Timeframe: M15

//@version=5
indicator("Price_Action_32", shorttitle="Price_Ac", overlay=false)

// Parâmetros
length = input.int(14, "Length", minval=1)
source = input.source(close, "Source")

// Cálculo
macd = ta.macd(source, length, length*2, length//2)

// Plot
plot(macd, "Price_Action_32", color=color.aqua)
