/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "SEFC"
#property link      "sefconfig@gmail.com"

#property indicator_chart_window
#property indicator_buffers 4
#property indicator_color1 Lime
#property indicator_color2 Orange
#property indicator_color3 Blue
#property indicator_color4 Red

extern int MA1Period = 8;
extern int MA1Method = 3;
extern int MA1Price = 5;
extern int MA2Period = 11;
extern int MA2Method = 3;
extern int MA2Price = 5;
double g_ibuf_100[];
double g_ibuf_104[];
double g_ibuf_108[];
double g_ibuf_112[];

int init() {
   SetIndexBuffer(0, g_ibuf_108);
   SetIndexStyle(0, DRAW_HISTOGRAM);
   SetIndexBuffer(1, g_ibuf_112);
   SetIndexStyle(1, DRAW_HISTOGRAM);
   SetIndexBuffer(2, g_ibuf_100);
   SetIndexBuffer(3, g_ibuf_104);
   StempelSEFC();
   return (0);
}

int deinit() {
   return (0);
}

int start() {
   int li_0 = IndicatorCounted();
   if (li_0 < 0) return (-1);
   if (li_0 > 0) li_0--;
   int li_4 = Bars - li_0;
   for (int li_8 = li_4; li_8 >= 0; li_8--) {
      g_ibuf_100[li_8] = iMA(NULL, 0, MA1Period, 0, MA1Method, MA1Price, li_8);
      g_ibuf_104[li_8] = iMA(NULL, 0, MA2Period, 1, MA2Method, MA2Price, li_8);
      g_ibuf_108[li_8] = g_ibuf_100[li_8];
      g_ibuf_112[li_8] = g_ibuf_104[li_8];
   }
   return (0);
}

void StempelSEFC() {
   ObjectCreate("Original Created by SEFC", OBJ_LABEL, 0, 0, 0);
   ObjectSetText("Original Created by SEFC", "SEFC *PALATO* - (Palato = Under earth Kingdom)", 8, "Lucida Handwriting", SpringGreen);
   ObjectSet("Original Created by SEFC", OBJPROP_CORNER, 2);
   ObjectSet("Original Created by SEFC", OBJPROP_XDISTANCE, 5);
   ObjectSet("Original Created by SEFC", OBJPROP_YDISTANCE, 10);
}
