/*
   Generated by EX4-TO-MQ4 decompiler V4.0.438.4 [-]
   Website: https://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "RoboFxId.Com"
#property link      "http://robofxid.com "

#property indicator_separate_window
#property indicator_minimum 0.0
#property indicator_maximum 1.2
#property indicator_buffers 2
#property indicator_color1 Green
#property indicator_color2 Red

extern int rook = 7;
int gi_80 = 400;
double gd_84 = 1.6;
double gd_92 = 50.6;
bool gi_100 = FALSE;
double gda_104[];
double gda_108[];
double gda_112[];
double gda_116[];
bool gi_120 = FALSE;
bool gi_124 = FALSE;

int init() {
   IndicatorBuffers(4);
   SetIndexStyle(0, DRAW_HISTOGRAM, STYLE_SOLID, 3);
   SetIndexBuffer(0, gda_112);
   SetIndexStyle(1, DRAW_HISTOGRAM, STYLE_SOLID, 3);
   SetIndexBuffer(1, gda_116);
   SetIndexStyle(2, DRAW_LINE, STYLE_SOLID, 2);
   SetIndexBuffer(2, gda_104);
   SetIndexStyle(3, DRAW_LINE, STYLE_SOLID, 2);
   SetIndexBuffer(3, gda_108);
   if (gi_80 >= Bars) gi_80 = Bars;
   SetIndexDrawBegin(0, Bars - gi_80 + rook);
   SetIndexDrawBegin(1, Bars - gi_80 + rook);
   return (0);
}

int start() {
   double ld_16;
   double ld_24;
   double ld_40;
   double ld_48;
   double ld_56;
   double ld_64;
   int li_12 = IndicatorCounted();
   if (Bars <= rook + 1) return (0);
   if (li_12 < rook + 1) {
      for (int li_0 = 1; li_0 <= rook; li_0++) gda_104[gi_80 - li_0] = 0.0;
      for (li_0 = 1; li_0 <= rook; li_0++) gda_108[gi_80 - li_0] = 0.0;
   }
   for (li_0 = gi_80 - rook; li_0 >= 0; li_0--) {
      ld_16 = High[iHighest(NULL, 0, MODE_HIGH, rook, li_0 - rook + 1)];
      ld_24 = Low[iLowest(NULL, 0, MODE_LOW, rook, li_0 - rook + 1)];
      ld_56 = NormalizeDouble(ld_24 - (ld_16 - ld_24) * gd_84 / 100.0, Digits);
      ld_64 = NormalizeDouble(ld_16 - (ld_16 - ld_24) * gd_92 / 100.0, Digits);
      gda_104[li_0 - rook + 6] = ld_64;
      gda_108[li_0 - rook - 1] = ld_64;
      if (gda_104[li_0 - rook + 6] >= gda_108[li_0 - rook + 6]) {
         gda_112[li_0 - rook + 6] = 1;
         gda_116[li_0 - rook + 6] = 0;
      } else {
         gda_116[li_0 - rook + 6] = 1;
         gda_112[li_0 - rook + 6] = 0;
      }
      ld_40 = gda_104[0];
      ld_48 = gda_108[0];
      if (ld_40 > ld_48) {
         if (gi_100 == TRUE && gi_124 == FALSE) {
            PlaySound("alert.wav");
            Alert("Short trend start @ " + DoubleToStr(ld_40, Digits) + " on " + Period() + " minute chart");
            gi_124 = TRUE;
            gi_120 = FALSE;
         }
      }
      if (ld_40 < ld_48) {
         if (gi_100 == TRUE && gi_120 == FALSE) {
            PlaySound("alert.wav");
            Alert("Long trend start @ " + DoubleToStr(ld_48, Digits) + " on " + Period() + " minute chart");
            gi_124 = FALSE;
            gi_120 = TRUE;
         }
      }
   }
   return (0);
}
